import { Inter } from "next/font/google";
import Navbar from './Component/Navbar';
import ReduxProvider from "./Redux/ReduxProvider";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
        <Navbar/>
        {children}
        </ReduxProvider>
        </body>
    </html>
  );
}
